const { PrismaClient } = require("@prisma/client");

const prisma = new PrismaClient();

const songs = [
  {
    title: "Honey Bee",
    artist: "Tom Petty",
    album: "Full Moon Fever",
    releaseDate: 1989,
    songsterrGuitarUrl: "https://www.ultimate-guitar.com/search.php?title=Honey+Bee+Tom+Petty&page=1&type=200",
    songsterrBassUrl: "https://www.ultimate-guitar.com/search.php?title=Honey+Bee+Tom+Petty&page=1&type=400",
    lyricsUrl: "https://genius.com/search?q=Honey+Bee+Tom+Petty",
    youtubeUrl: "https://www.youtube.com/watch?v=jY4j98YYvEw",
  },
  {
    title: "Death Valley Queen",
    artist: "Flogging Molly",
    album: "Drunken Lullabies",
    releaseDate: 2002,
    songsterrGuitarUrl: "https://www.songsterr.com/a/wa/search?pattern=Death%20Valley%20Queen%20Flogging%20Molly",
    lyricsUrl: "https://www.google.com/search?q=Death+Valley+Queen+Flogging+Molly+lyrics",
    youtubeUrl: "https://www.youtube.com/results?search_query=Death+Valley+Queen+Flogging+Molly",
  },
  {
    title: "Yellow",
    artist: "Coldplay",
    album: "Parachutes",
    releaseDate: 2000,
    songsterrGuitarUrl: "https://www.songsterr.com/a/wsa/coldplay-yellow-tab-s434",
    lyricsUrl: "https://www.google.com/search?q=Yellow+Coldplay+lyrics",
    youtubeUrl: "https://www.youtube.com/results?search_query=Yellow+Coldplay",
  },
  {
    title: "Green River",
    artist: "Creedence Clearwater Revival",
    album: "Green River",
    releaseDate: 1969,
    songsterrGuitarUrl: "https://www.songsterr.com/a/wa/search?pattern=Green%20River%20Creedence",
    songsterrBassUrl: "https://www.songsterr.com/a/wa/search?pattern=Green%20River%20Creedence%20bass",
    lyricsUrl: "https://www.google.com/search?q=Green+River+Creedence+Clearwater+Revival+lyrics",
    youtubeUrl: "https://www.youtube.com/results?search_query=Green+River+Creedence+Clearwater+Revival",
  },
  {
    title: "Something in the Orange",
    artist: "Zach Bryan",
    album: "DeAnn",
    releaseDate: 2022,
    songsterrGuitarUrl: "https://www.songsterr.com/a/wa/search?pattern=Something%20in%20the%20Orange%20Zach%20Bryan",
    lyricsUrl: "https://www.google.com/search?q=Something+in+the+Orange+Zach+Bryan+lyrics",
    youtubeUrl: "https://www.youtube.com/results?search_query=Something+in+the+Orange+Zach+Bryan",
  },
  {
    title: "Slide",
    artist: "Goo Goo Dolls",
    album: "Dizzy Up the Girl",
    releaseDate: 1998,
    songsterrGuitarUrl: "https://www.songsterr.com/a/wsa/goo-goo-dolls-slide-tab-s1262",
    songsterrBassUrl: "https://www.songsterr.com/a/wa/search?pattern=Slide%20Goo%20Goo%20Dolls%20bass",
    lyricsUrl: "https://www.google.com/search?q=Slide+Goo+Goo+Dolls+lyrics",
    youtubeUrl: "https://www.youtube.com/results?search_query=Slide+Goo+Goo+Dolls",
  },
  {
    title: "Mountain Sound",
    artist: "Of Monsters and Men",
    album: "My Head Is an Animal",
    releaseDate: 2011,
    songsterrGuitarUrl: "https://www.songsterr.com/a/wa/search?pattern=Mountain%20Sound%20Of%20Monsters%20and%20Men",
    lyricsUrl: "https://www.google.com/search?q=Mountain+Sound+Of+Monsters+and+Men+lyrics",
    youtubeUrl: "https://www.youtube.com/results?search_query=Mountain+Sound+Of+Monsters+and+Men",
  },
  {
    title: "Holdin' Heaven",
    artist: "Tracy Byrd",
    album: "Don't Throw Stones",
    releaseDate: 1994,
    songsterrGuitarUrl: "https://www.songsterr.com/a/wa/search?pattern=Holdin%20Heaven%20Tracy%20Byrd",
    lyricsUrl: "https://www.google.com/search?q=Holdin+Heaven+Tracy+Byrd+lyrics",
    youtubeUrl: "https://www.youtube.com/results?search_query=Holdin+Heaven+Tracy+Byrd",
  },
  {
    title: "Oh Pretty Woman",
    artist: "Albert King",
    album: "Stax Volt Records",
    releaseDate: 1967,
    songsterrGuitarUrl: "https://www.songsterr.com/a/wa/search?pattern=Oh%20Pretty%20Woman%20Albert%20King",
    lyricsUrl: "https://www.google.com/search?q=Oh+Pretty+Woman+Albert+King+lyrics",
    youtubeUrl: "https://www.youtube.com/results?search_query=Oh+Pretty+Woman+Albert+King",
  },
  {
    title: "Can't You See",
    artist: "Marshall Tucker Band",
    album: "The Marshall Tucker Band",
    releaseDate: 1973,
    songsterrGuitarUrl: "https://www.songsterr.com/a/wsa/marshall-tucker-band-cant-you-see-tab-s10000",
    songsterrBassUrl: "https://www.songsterr.com/a/wa/search?pattern=Can't%20You%20See%20Marshall%20Tucker%20bass",
    lyricsUrl: "https://www.google.com/search?q=Can't+You+See+Marshall+Tucker+Band+lyrics",
    youtubeUrl: "https://www.youtube.com/results?search_query=Can't+You+See+Marshall+Tucker+Band",
  },
  {
    title: "That's Just About Right",
    artist: "Blackhawk",
    album: "Blackhawk",
    releaseDate: 1994,
    songsterrGuitarUrl: "https://www.songsterr.com/a/wa/search?pattern=That's%20Just%20About%20Right%20Blackhawk",
    lyricsUrl: "https://www.google.com/search?q=That's+Just+About+Right+Blackhawk+lyrics",
    youtubeUrl: "https://www.youtube.com/results?search_query=That's+Just+About+Right+Blackhawk",
  },
  {
    title: "Gild the Lily",
    artist: "Billy Strings",
    album: "Renewal",
    releaseDate: 2023,
    songsterrGuitarUrl: "https://www.songsterr.com/a/wa/search?pattern=Gild%20the%20Lily%20Billy%20Strings",
    lyricsUrl: "https://www.google.com/search?q=Gild+the+Lily+Billy+Strings+lyrics",
    youtubeUrl: "https://www.youtube.com/results?search_query=Gild+the+Lily+Billy+Strings",
  },
  {
    title: "Guys Do It All the Time",
    artist: "Mindy McCready",
    album: "Ten Thousand Angels",
    releaseDate: 1994,
    songsterrGuitarUrl: "https://www.songsterr.com/a/wa/search?pattern=Guys%20Do%20It%20All%20the%20Time%20Mindy%20McCready",
    lyricsUrl: "https://www.google.com/search?q=Guys+Do+It+All+the+Time+Mindy+McCready+lyrics",
    youtubeUrl: "https://www.youtube.com/results?search_query=Guys+Do+It+All+the+Time+Mindy+McCready",
  },
  {
    title: "Whiskey, Women & Wild Rides",
    artist: "Cody M Brooks",
    album: "Independence",
    releaseDate: 2014,
    songsterrGuitarUrl: "https://www.songsterr.com/a/wa/search?pattern=Whiskey%20Women%20Wild%20Rides%20Cody%20Brooks",
    lyricsUrl: "https://www.google.com/search?q=Whiskey+Women+Wild+Rides+Cody+Brooks+lyrics",
    youtubeUrl: "https://www.youtube.com/results?search_query=Whiskey+Women+Wild+Rides+Cody+Brooks",
  },
  {
    title: "Nobody to Blame",
    artist: "Chris Stapleton",
    album: "Traveller",
    releaseDate: 2015,
    songsterrGuitarUrl: "https://www.songsterr.com/a/wa/search?pattern=Nobody%20to%20Blame%20Chris%20Stapleton",
    songsterrBassUrl: "https://www.songsterr.com/a/wa/search?pattern=Nobody%20to%20Blame%20Chris%20Stapleton%20bass",
    lyricsUrl: "https://www.google.com/search?q=Nobody+to+Blame+Chris+Stapleton+lyrics",
    youtubeUrl: "https://www.youtube.com/results?search_query=Nobody+to+Blame+Chris+Stapleton",
  },
  {
    title: "Seasons of Wither",
    artist: "Aerosmith",
    album: "Dream On",
    releaseDate: 1973,
    songsterrGuitarUrl: "https://www.songsterr.com/a/wa/search?pattern=Seasons%20of%20Wither%20Aerosmith",
    songsterrBassUrl: "https://www.songsterr.com/a/wa/search?pattern=Seasons%20of%20Wither%20Aerosmith%20bass",
    lyricsUrl: "https://www.google.com/search?q=Seasons+of+Wither+Aerosmith+lyrics",
    youtubeUrl: "https://www.youtube.com/results?search_query=Seasons+of+Wither+Aerosmith",
  },
  {
    title: "Slow Dancing in a Burning Room",
    artist: "John Mayer",
    album: "Continuum",
    releaseDate: 2006,
    songsterrGuitarUrl: "https://tabs.ultimate-guitar.com/tab/john-mayer/slow-dancing-in-a-burning-room-chords-443060",
    songsterrBassUrl: "https://www.ultimate-guitar.com/search.php?title=Slow+Dancing+in+a+Burning+Room+John+Mayer&page=1&type=400",
    lyricsUrl: "https://www.google.com/search?q=Slow+Dancing+in+a+Burning+Room+John+Mayer+lyrics",
    youtubeUrl: "https://www.youtube.com/results?search_query=Slow+Dancing+in+a+Burning+Room+John+Mayer",
  },
  {
    title: "Love Is a Battlefield",
    artist: "Pat Benatar",
    album: "Love Is a Battlefield",
    releaseDate: 1983,
    songsterrGuitarUrl: "https://www.songsterr.com/a/wa/search?pattern=Love%20Is%20a%20Battlefield%20Pat%20Benatar",
    lyricsUrl: "https://www.google.com/search?q=Love+Is+a+Battlefield+Pat+Benatar+lyrics",
    youtubeUrl: "https://www.youtube.com/results?search_query=Love+Is+a+Battlefield+Pat+Benatar",
  },
  {
    title: "Crimson and Clover",
    artist: "Joan Jett",
    album: "Album",
    releaseDate: 1982,
    songsterrGuitarUrl: "https://www.songsterr.com/a/wa/search?pattern=Crimson%20and%20Clover%20Joan%20Jett",
    songsterrBassUrl: "https://www.songsterr.com/a/wa/search?pattern=Crimson%20and%20Clover%20Joan%20Jett%20bass",
    lyricsUrl: "https://www.google.com/search?q=Crimson+and+Clover+Joan+Jett+lyrics",
    youtubeUrl: "https://www.youtube.com/results?search_query=Crimson+and+Clover+Joan+Jett",
  },
  {
    title: "I Hate Myself for Loving You",
    artist: "Joan Jett & The Blackhearts",
    album: "Up Your Alley",
    releaseDate: 1988,
    songsterrGuitarUrl: "https://www.songsterr.com/a/wa/search?pattern=I%20Hate%20Myself%20for%20Loving%20You",
    songsterrBassUrl: "https://www.songsterr.com/a/wa/search?pattern=I%20Hate%20Myself%20for%20Loving%20You%20bass",
    lyricsUrl: "https://www.google.com/search?q=I+Hate+Myself+for+Loving+You+Joan+Jett+lyrics",
    youtubeUrl: "https://www.youtube.com/results?search_query=I+Hate+Myself+for+Loving+You+Joan+Jett",
  },
  {
    title: "Long Run",
    artist: "The Eagles",
    album: "The Long Run",
    releaseDate: 1979,
    songsterrGuitarUrl: "https://www.songsterr.com/a/wa/search?pattern=Long%20Run%20Eagles",
    songsterrBassUrl: "https://www.songsterr.com/a/wa/search?pattern=Long%20Run%20Eagles%20bass",
    lyricsUrl: "https://www.google.com/search?q=Long+Run+Eagles+lyrics",
    youtubeUrl: "https://www.youtube.com/results?search_query=Long+Run+Eagles",
  },
  {
    title: "Breakdown",
    artist: "Tom Petty and the Heartbreakers",
    album: "Damn the Torpedoes",
    releaseDate: 1979,
    songsterrGuitarUrl: "https://www.songsterr.com/a/wa/search?pattern=Breakdown%20Tom%20Petty",
    songsterrBassUrl: "https://www.songsterr.com/a/wa/search?pattern=Breakdown%20Tom%20Petty%20bass",
    lyricsUrl: "https://www.google.com/search?q=Breakdown+Tom+Petty+lyrics",
    youtubeUrl: "https://www.youtube.com/results?search_query=Breakdown+Tom+Petty",
  },
  {
    title: "That's How Every Empire Falls",
    artist: "John Prine",
    album: "In Spite of Ourselves",
    releaseDate: 1999,
    songsterrGuitarUrl: "https://www.songsterr.com/a/wa/search?pattern=That's%20How%20Every%20Empire%20Falls",
    lyricsUrl: "https://www.google.com/search?q=That's+How+Every+Empire+Falls+John+Prine+lyrics",
    youtubeUrl: "https://www.youtube.com/results?search_query=That's+How+Every+Empire+Falls+John+Prine",
  },
  {
    title: "Dangerous",
    artist: "Roxette",
    album: "Look Sharp!",
    releaseDate: 1988,
    songsterrGuitarUrl: "https://www.songsterr.com/a/wa/search?pattern=Dangerous%20Roxette",
    lyricsUrl: "https://www.google.com/search?q=Dangerous+Roxette+lyrics",
    youtubeUrl: "https://www.youtube.com/results?search_query=Dangerous+Roxette",
  },
  {
    title: "Sold",
    artist: "John Michael Montgomery",
    album: "Sold",
    releaseDate: 1994,
    songsterrGuitarUrl: "https://www.songsterr.com/a/wa/search?pattern=Sold%20John%20Michael%20Montgomery",
    lyricsUrl: "https://www.google.com/search?q=Sold+John+Michael+Montgomery+lyrics",
    youtubeUrl: "https://www.youtube.com/results?search_query=Sold+John+Michael+Montgomery",
  },
  {
    title: "Folsom Prison Blues",
    artist: "Johnny Cash",
    album: "At Folsom Prison",
    releaseDate: 1968,
    songsterrGuitarUrl: "https://www.songsterr.com/a/wa/search?pattern=Folsom%20Prison%20Blues%20Johnny%20Cash",
    songsterrBassUrl: "https://www.songsterr.com/a/wa/search?pattern=Folsom%20Prison%20Blues%20Johnny%20Cash%20bass",
    lyricsUrl: "https://www.google.com/search?q=Folsom+Prison+Blues+Johnny+Cash+lyrics",
    youtubeUrl: "https://www.youtube.com/results?search_query=Folsom+Prison+Blues+Johnny+Cash",
  },
  {
    title: "Dirty Little Secret",
    artist: "The All-American Rejects",
    album: "Move Along",
    releaseDate: 2006,
    songsterrGuitarUrl: "https://www.songsterr.com/a/wa/search?pattern=Dirty%20Little%20Secret%20All-American%20Rejects",
    songsterrBassUrl: "https://www.songsterr.com/a/wa/search?pattern=Dirty%20Little%20Secret%20All-American%20Rejects%20bass",
    lyricsUrl: "https://www.google.com/search?q=Dirty+Little+Secret+All-American+Rejects+lyrics",
    youtubeUrl: "https://www.youtube.com/results?search_query=Dirty+Little+Secret+All-American+Rejects",
  },
  {
    title: "Stacy's Mom",
    artist: "Fountains of Wayne",
    album: "Fountains of Wayne",
    releaseDate: 1996,
    songsterrGuitarUrl: "https://www.songsterr.com/a/wa/search?pattern=Stacy's%20Mom%20Fountains%20of%20Wayne",
    songsterrBassUrl: "https://www.songsterr.com/a/wa/search?pattern=Stacy's%20Mom%20Fountains%20of%20Wayne%20bass",
    lyricsUrl: "https://www.google.com/search?q=Stacy's+Mom+Fountains+of+Wayne+lyrics",
    youtubeUrl: "https://www.youtube.com/results?search_query=Stacy's+Mom+Fountains+of+Wayne",
  },
  {
    title: "Don't Stop Believin'",
    artist: "Journey",
    album: "Escape",
    releaseDate: 1981,
    songsterrGuitarUrl: "https://www.songsterr.com/a/wa/search?pattern=Don't%20Stop%20Believin'%20Journey",
    songsterrBassUrl: "https://www.ultimate-guitar.com/search.php?title=Don't+Stop+Believin'+Journey&page=1&type=400",
    lyricsUrl: "https://www.google.com/search?q=Don't+Stop+Believin'+Journey+lyrics",
    youtubeUrl: "https://www.youtube.com/results?search_query=Don't+Stop+Believin'+Journey",
  },
  {
    title: "The Ballad of Jayne",
    artist: "L.A. Guns",
    album: "Cocked & Loaded",
    releaseDate: 1989,
    songsterrGuitarUrl: "https://www.songsterr.com/a/wa/search?pattern=The%20Ballad%20of%20Jayne%20LA%20Guns",
    songsterrBassUrl: "https://www.songsterr.com/a/wa/search?pattern=The%20Ballad%20of%20Jayne%20LA%20Guns%20bass",
    lyricsUrl: "https://www.google.com/search?q=The+Ballad+of+Jayne+LA+Guns+lyrics",
    youtubeUrl: "https://www.youtube.com/results?search_query=The+Ballad+of+Jayne+LA+Guns",
  },
  {
    title: "Roadhouse Blues",
    artist: "The Black Moods",
    album: "The Black Moods",
    releaseDate: 2021,
    songsterrGuitarUrl: "https://www.songsterr.com/a/wa/search?pattern=Roadhouse%20Blues%20Black%20Moods",
    lyricsUrl: "https://www.google.com/search?q=Roadhouse+Blues+Black+Moods+lyrics",
    youtubeUrl: "https://www.youtube.com/results?search_query=Roadhouse+Blues+Black+Moods",
  },
  {
    title: "Sugar Sweet",
    artist: "Jeff Healey",
    album: "See the Light",
    releaseDate: 1988,
    songsterrGuitarUrl: "https://www.songsterr.com/a/wa/search?pattern=Sugar%20Sweet%20Jeff%20Healey",
    songsterrBassUrl: "https://www.songsterr.com/a/wa/search?pattern=Sugar%20Sweet%20Jeff%20Healey%20bass",
    lyricsUrl: "https://www.google.com/search?q=Sugar+Sweet+Jeff+Healey+lyrics",
    youtubeUrl: "https://www.youtube.com/results?search_query=Sugar+Sweet+Jeff+Healey",
  },
  {
    title: "Cold Shot",
    artist: "Stevie Ray Vaughan & Double Trouble",
    album: "Soul to Soul",
    releaseDate: 1989,
    songsterrGuitarUrl: "https://www.songsterr.com/a/wsa/stevie-ray-vaughan-cold-shot-tab-s446708",
    songsterrBassUrl: "https://www.ultimate-guitar.com/search.php?title=Cold+Shot+Stevie+Ray+Vaughan&page=1&type=400",
    lyricsUrl: "https://www.google.com/search?q=Cold+Shot+Stevie+Ray+Vaughan+lyrics",
    youtubeUrl: "https://www.youtube.com/results?search_query=Cold+Shot+Stevie+Ray+Vaughan",
  },
];

async function main() {
  try {
    // Clear existing songs
    await prisma.song.deleteMany({});
    console.log("Cleared existing songs");

    // Add new songs
    for (const song of songs) {
      await prisma.song.create({ data: song });
    }
    console.log(`✓ Seeded ${songs.length} songs with resources and album info`);
  } catch (error) {
    console.error("Seed error:", error);
    process.exit(1);
  } finally {
    await prisma.$disconnect();
  }
}

main();
